<?php

/**
 * @file
 *   buckaroo.module
 *   Payment gateway for Buckaroo
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/**
 * Implementation of hook_init().
 */
function buckaroo_init() {
  $post = $GLOBALS['_POST'];

  if (!empty($post['bpe_result'])) {
    $error_codes = _buckaroo_get_error_codes();
    if ($error_codes[$post['bpe_result']]) {
      $status = $error_codes[$post['bpe_result']]['error_level'];
      //Change 'success' to drupal_set_message default status
      if ($status == 'success') {
        $status = 'status' ;
      }
      drupal_set_message($error_codes[$post['bpe_result']]['message'], $status);
    }
    // CiviCRM integration
    if (module_exists('civi_api')) {
      $civi_config = civi_get_config();
      //Check if CiviContribute is enabled
      if (in_array('CiviContribute', $civi_config->enableComponents)) {

      }
    }
  }
  dsm(get_defined_vars());
}

/**
 * Implements of hook_perm().
 *
 * @return array An array of valid permissions for the buckaroo module
 */
function buckaroo_permission() {
  return array(
    'administer buckaroo' => array(
      'title' => t('Administer Buckaroo'),
      'description' => t('Administer buckaroo'),
    ),
    'access buckaroo' => array(
      'title' => t('Access Buckaroo payment form'),
    ),
  );
}
/**
 * Implemens hook_menu().
 *
 * @return An array of menu items.
 */
function buckaroo_menu() {
  $items = array();

  $items['admin/config/buckaroo'] = array(
    'title' => 'Buckaroo',
    'description' => 'Settings for Buckaroo payment gateway.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('buckaroo_admin_form'),
    'access arguments' => array('administer buckaroo'),
    'file' => 'includes/buckaroo.admin.inc',
  );

  $buckaroo_menu = variable_get('BPE_path', 'buckaroo');

  if (substr($buckaroo_menu, 0, 4) != 'node') {
    $items[$buckaroo_menu] = array(
      'title' => 'Buckaroo payment page',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('buckaroo_payment_form'),
      'access arguments' => array('access buckaroo'),
      'file' => 'includes/buckaroo.form.inc',
    );
  }

//  if (!menu_get_item($buckaroo_menu)) {
//
//  }

  return $items;
}

function buckaroo_form_alter(&$form, $form_state, $form_id) {
  //dsm($form_id);
}

/*
 * Implements hook_form_FORM_ID_alter
 * Need to alter our admin form, because our submit function need to run last
 */
function buckaroo_form_buckaroo_admin_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'buckaroo_admin_form_submit';
}

/**
 * Get all payment methods, it's names and it's enabled or not
 * @todo: make this configurable
 * @return array
 *   And array of predefined payment methods
 */
function buckaroo_get_payment_methods() {
  $defaults = &drupal_static(__FUNCTION__);

  if (isset($defaults)) {
    return $defaults;
  }

  $defaults = array(
    'cc' => array(
      'name'=> 'Credit cards',
      'description' => t('You will be redirected to a Credit Card placeholder to complete the payment.'),
      'action' => 'https://payment.buckaroo.nl/sslplus/request_for_authorization.asp',
     ),
    'ideal' => array(
      'name'=> t('iDEAL'),
      'description' => t('You will be redirected to the iDEAL system to complete the payment.'),
      'action' => 'https://payment.buckaroo.nl/gateway/ideal_payment.asp',
     ),
    'gp' => array(
      'name'=> t('Giropay'),
     ),
    'pp' => array(
      'name'=> t('PayPal'),
      'description' => t('Pay using your PayPal account. You will be redirected to the PayPal system to complete the payment.'),
      'action' => 'https://payment.buckaroo.nl/gateway/paypal_payment.asp',
     ),
    'oodb' => array(
      'name'=> t('Once-only and continuous direct debits'),
     ),
   );
  foreach ($defaults as $key => &$value) {
    $value['enabled'] = buckaroo_get_enabled($key) ;
  }
  return $defaults;
}

function buckaroo_get_enabled($machine_name) {
  return variable_get("BPE_{$machine_name}_enabled", 0);
}

/**
 * Get all Buckaroo variables
 * @return array
 *   An array of all variables defined by this module
 */
function buckaroo_variable_get() {
  $vars = array(
    'path' => variable_get('BPE_path', 'buckaroo'),
    'merchant_key' => variable_get('BPE_Merchant', ''),
    'secret_key' => variable_get('BPE_SecretKey', ''),
    'amount_title' => variable_get('BPE_amount_title', 'Choose an ammount'),
    'amount_values' => variable_get('BPE_amount_values', array('5', '10')),
    'currency' => variable_get('BPE_Currency', 'EUR'),
    'unique_amount' => variable_get('BPE_unique_amount', ''),
    'method_title' => variable_get('BPE_method_title', 'Choose your payment method'),
    'civi_title' => variable_get('BPE_civi_title', 'Enter your details'),
    'civi_profile' => variable_get('BPE_civi_profile', 'none'),
    'civi_position' => variable_get('BPE_civi_position', 0),
    'mode' => variable_get('BPE_Mode', 0),
  );
  $vars += buckaroo_get_payment_methods();
  return $vars;
}

function buckaroo_create_signature($machine_name) {
  $vars = buckaroo_variable_get();
  $ammount = isset($_GET['default_amount']) ? $_GET['default_amount'] * 100 : $vars['amount_values'][0] * 100;
  $string = $vars['merchant_key'] . buckaroo_create_invoice() .$ammount . $vars['currency'] . $vars['mode'] . $vars['secret_key'];
  return md5($string);
}

function buckaroo_create_invoice() {
  $invoice = &drupal_static(__FUNCTION__, "panparks-" . time());
  return $invoice;
}

function buckaroo_xmlrpc($form, $form_state) {
  // First define the endpoint of the XML-RPC service, in this case is our
  // own server.
  $server = url('https://payment.buckaroo.nl/xml/request_for_authorization_mpi.asp', array('external' => TRUE));
  // Then we should define the method to call. xmlrpc() requires that all the
  // information related to the called method is passed as an array in the form
  // of 'method_name' => arguments_array
  $options = array(
    'xmlrpc_example.add' => array(
      (int) $form_state['values']['num1'],
      (int) $form_state['values']['num2'],
    ),
  );
  // Make the xmlrpc request and process the results.
  $result = xmlrpc($server, $options);
  if ($result === FALSE) {
    drupal_set_message(
      t('Error return from xmlrpc(): Error: @errno, Message: @message',
      array('@errno' => xmlrpc_errno(), '@message' => xmlrpc_error_msg())),
      'error'
    );
  }
  else {
    drupal_set_message(
      t('The XML-RPC server returned this response: @response',
      array('@response' => print_r($result, TRUE)))
    );
  }
}

/**
 * Helper function to read statuscodes.csv
 * @todo: make the messages trasnlatable
 * @return array
 */
function _buckaroo_get_error_codes() {
  $file = drupal_get_path('module', 'buckaroo') . '/statuscodes.csv';

  $header = array('status_code', 'message', 'error_level');;
  $data = array();
  $csvData = str_getcsv($file, "\n");

  foreach ($csvData as $csvLine) {
      $items = explode(';', $csvLine);
      for ($n = 0, $m = count($header); $n < $m; $n++) {
        $prepareData[$header[$n]] = $items[$n];
      }
      $data[$prepareData['status_code']] = $prepareData;
  }
  return $data;
}
